# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :_run do
  clean_build_artifacts
  sh("rm -rf ./output || true")
  clear_derived_data
  cocoapods(use_bundle_exec: false, try_repo_update_on_error: true)
  scan(
    	scheme: "TaskTracker",
    	device: "iPhone 11",
    	disable_concurrent_testing: true,
    	suppress_xcode_output: false,
    	reset_simulator: false,
    	prelaunch_simulator: true,
    	clean: false,
    	output_directory: './output/xcov',
    	only_testing: 'TaskTrackerTests'
  )
  end
end
